export const UZ_SMS_PANEL = 'UZ_SMS_PANEL';

export const MODELS = {
  USER: 'USER',
  TRANSACTION: 'TRANSACTION',
  CONTACT: 'CONTACT',
  OTP: 'OTP',
  SMS_CAMPAIGN: 'SMS_CAMPAIGN',
  SMS_COMPANY: 'SMS_COMPANY',
  SMS_CONTACT: 'SMS_CONTACT',
  SMS_GROUP: 'SMS_GROUP',
  SMS_MESSAGE: 'SMS_MESSAGE',
  SMS_PRICE: 'SMS_PRICE',
  SMS_TEMPLATE: 'SMS_TEMPLATE',
  SMS_SENDER: 'SMS_SENDER',
  SENDER_PRICE: 'SENDER_PRICE',
  TARIFFS: 'TARIFFS',
  FILE: 'FILE',
};
