export const UZ_SMS_PANEL = 'UZ_SMS_PANEL';

export const MODELS = {
  USER: 'USER',
  API_KEY: 'API_KEY',
  BALANCE_TRANSACTION: 'BALANCE_TRANSACTION',
  CONTACT: 'CONTACT',
  OTP: 'OTP',
  SMS_CAMPAIGN: 'SMS_CAMPAIGN',
  SMS_COMPANY: 'SMS_COMPANY',
  SMS_CONTACT: 'SMS_CONTACT',
  SMS_GROUP: 'SMS_GROUP',
  SMS_MESSAGE: 'SMS_MESSAGE',
  SMS_PRICE: 'SMS_PRICE',
  SMS_TEMPLATE: 'SMS_TEMPLATE',
  TARIFFS: 'TARIFFS',
};
