export const UZ_SMS_PANEL = 'UZ_SMS_PANEL';

export const MODELS = {
  USER: 'USER',
  TRANSACTION: 'TRANSACTION',
  CONTACT: 'CONTACT',
  OTP: 'OTP',
  SMS_CONTACT: 'SMS_CONTACT',
  SMS_GROUP: 'SMS_GROUP',
  SMS_MESSAGE: 'SMS_MESSAGE',
  SMS_TEMPLATE: 'SMS_TEMPLATE',
  SMS_SENDER: 'SMS_SENDER',
  SENDER_PRICE: 'SENDER_PRICE',
  TARIFFS: 'TARIFFS',
  COUNTRY: 'COUNTRY',
  FILE: 'FILE',
  EMAIL_CONTACT: 'EMAIL_CONTACT',
  EMAIL_GROUP: 'EMAIL_GROUP',
  EMAIL_MESSAGE: 'EMAIL_MESSAGE',
  EMAIL_SMTP: 'EMAIL_SMTP',
  EMAIL_TEMPLATE: 'EMAIL_TEMPLATE',
};

export const SMS_CONTACT_QUEUE = 'smsContactNtfQueueGF';
export const SMS_MESSAGE_QUEUE = 'smsMessageNtfQueueGF';
