version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fix-back-prod-postgres
    environment:
      POSTGRES_DB: stroy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - fix-back-prod-network

  redis:
    image: redis:7-alpine
    container_name: fix-back-prod-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data_prod:/data
    networks:
      - fix-back-prod-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: fix-back-prod-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data_prod:/usr/share/elasticsearch/data
    networks:
      - fix-back-prod-network

  dashboard-app:
    image: ${DASHBOARD_IMAGE:-ghcr.io/gafurov8020/fix-back-dashboard:latest}
    container_name: fix-back-prod-dashboard
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - '5050:4041'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: stroy_db
      DB_SCHEMA: public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      DASHBOARD_PORT: 4041
      JWT_SECRET: 0e5de417b661eae3950461dfdbb7f855a09de59bbfb92555c71727aa5334dc5c
      SYNCHRONIZE: true
      MEDIA_DIRECTORY: uploads
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - uploads_data_prod:/app/uploads
    networks:
      - fix-back-prod-network

  frontend-app:
    image: ${FRONTEND_IMAGE:-ghcr.io/gafurov8020/fix-back-frontend:latest}
    container_name: fix-back-prod-frontend
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - '5151:4141'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: stroy_db
      DB_SCHEMA: public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      FRONTEND_PORT: 4141
      JWT_SECRET: 0e5de417b661eae3950461dfdbb7f855a09de59bbfb92555c71727aa5334dc5c
      SYNCHRONIZE: true
      MEDIA_DIRECTORY: uploads
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - uploads_data_prod:/app/uploads
    networks:
      - fix-back-prod-network

volumes:
  postgres_data_prod:
  redis_data_prod:
  elasticsearch_data_prod:
  uploads_data_prod:

networks:
  fix-back-prod-network:
    driver: bridge